Repository AkshitLakhera/PenCraft-Full-Stack-Blogging-Application, pull requests merged in 2024-10, with the labels that each got.

#37 Fixed #27 : Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#33 Enhance Appbar with Mode Toggle and Mobile Responsiveness for /blog Route
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Appbar.tsx
  frontend/src/components/BlogCard.tsx
  frontend/src/components/CompleteBlog.tsx
  frontend/src/components/mode-toggle.tsx
  frontend/src/components/theme-provider.tsx
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/menubar.tsx
  frontend/src/config.ts
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/src/pages/Blog.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: gssoc-ext, level2, hacktoberfest-accepted

#46 Create LICENSE.txt #44
  LICENSE.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1

#53 Fixed styling around buttons
  frontend/src/pages/Landing.tsx
Labels: gssoc-ext, level1, hacktoberfest2024

#50 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#58 Implement search functionality for navigating long blogs (Fixes #31)
  backend/src/routes/blog.ts
  frontend/package-lock.json
  frontend/src/components/CompleteBlog.tsx
  package-lock.json
Labels: gssoc-ext, level2, hacktoberfest2024

#61 FIX: Fixed the Comments Number
  frontend/src/components/CompleteBlog.tsx
Labels: gssoc-ext, level1, hacktoberfest2024

#64 FIX: Made the Blog Post Page Responsive
  frontend/src/components/CompleteBlog.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#67 #59 Added Special Email and password regex expression for form validation which do not allow special characters and view password button
  frontend/src/components/Auth.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest2024

#69 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#71 ui of signup and sigin updated for light mode
  frontend/src/components/ui/SignIn.tsx
  frontend/src/components/ui/SignUp.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#79 Fix Contributor Links in README by Updating Username Extraction Logic
  .github/workflows/update_contributors.yml
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#103 Update UI for MyBlogs page (Closes #95)
  frontend/src/pages/Myblogs.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#97 Implement Lenis (Closes #26)
  README.md
  frontend/package.json
  frontend/src/App.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#106 Added the Contributor page to /contributor route with proper theme and structure.
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/pages/ContributorPage.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest2024

#123 Fixed SignUp Page
  frontend/src/components/ui/SignUp.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#120 Fix: Issue #32
  frontend/src/assets/hero-pen.png
  frontend/src/components/ui/AboutUs.tsx
  frontend/src/components/ui/Blog.tsx
  frontend/src/components/ui/Explore.tsx
  frontend/src/pages/Landing.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest2024

#119 Updated Images in README.md File
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024

#133 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr_checker.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#137 added google translator
  frontend/src/App.tsx
  frontend/src/components/GTranslateLoader.tsx
  frontend/src/index.css
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest2024

#134 Added X Logo | Issue #109
  frontend/src/components/ui/SignIn.tsx
  frontend/src/components/ui/SignUp.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted, level1, hacktoberfest2024

#142 added chatbot
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/Chatbot.tsx
Labels: gssoc-ext, level2, hacktoberfest-accepted, hacktoberfest2024

#147 Ui: make the whole homepage responsive #146
  frontend/src/components/ui/AboutUs.tsx
  frontend/src/components/ui/Explore.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#114 Fixes #111: Height of Landing Page
  frontend/src/pages/Landing.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest2024
